### ISSUE TITLE
Tailwind CSS does not work

### ISSUE THREAD

**Issue by Sergey98Am** [strarsis/sage10-fse#3]
Tailwind CSS does not work, I have tried `npm run dev` and `npm run build`, but the result is the same

![Screenshot from 2024-05-30 22-12-06](https://github.com/strarsis/sage10-fse/assets/52923458/e78d797b-7789-40b3-9eb5-38df1e5c5289)

**Comment by strarsis** [comment]
@Sergey98Am: Indeed, for whatever reason the `app.blade.php` classic Blade-PHP view had some markup missing (hence no app.css was actually added).
The latest release [re-added the markup](https://github.com/strarsis/sage10-fse/commit/c71e3a8bdf95e75dbd9de05919d7ecb1950fc814) and it works now with Tailwind styles:
https://github.com/strarsis/sage10-fse/releases/tag/v2.2.0

**Comment by strarsis** [comment]
Fixed: https://github.com/strarsis/sage10-fse/commit/c71e3a8bdf95e75dbd9de05919d7ecb1950fc814
